language: r
sudo: required
cache: packages

git:
  depth: 3

env:
  global:
    - secure: GITHUB_PAT

r_packages:
 - devtools
 - dplyr
 - ggplot2

install:
    # Install pandoc 1.18 to squash warning messages
  - curl -L https://github.com/jgm/pandoc/releases/download/1.18/pandoc-1.18-1-amd64.deb > pandoc-1.18-1-amd64.deb
  - sudo dpkg -i pandoc-1.18-1-amd64.deb
  - sudo apt-get install -f
  - Rscript -e "if (!require('devtools')) install.packages('devtools')"
  - Rscript -e "devtools::install_github('ukgovdatascience/eesectors')"
  - Rscript -e "devtools::install_github('ukgovdatascience/govstyle')"


before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
